### ISSUE TITLE
problems running test on SUNCG

### ISSUE THREAD

**Issue by yinlingluo** [Sekunde/3D-SIS#7]
Hi!
I am running test on SUNCG test data (followed the instructions in README/Inference on SUNCG dataset).
Q1: Should in Inference on SUNCG dataset/3, should we modify experiments/cfgs/ScanNet/benchmark.yml or experiments/cfgs/SUNCG/rpn_class_mask_5.yml?

Then I modified both and try to run the test.
Q2: Those images files cannot be accessed since scene_name(defined in dataset.py/151) refers to first chunk(before"__0__") of scene_name, while all those real scene_names (as in suncg_test_data/images; suncg_test_data/scenes downloaded from given link) include the "__0__".

Then I tried either modify the directory names for those scenes in suncg_test_data/images or just change the definition of scene_name to include the "__0__".
Q3: 
But then, after "starting test on whole scan..."
I got:
error: no invalid depth
error: no invalid depth
error: no invalid depth
[path to the scene file]:(invalid sample: no valid projection)
and this seems further caused "CUDA error:out of memory" issue

Is there anything I can do to solve this?
Thanks!

**Comment by Sekunde** [comment]
Q1: experiments/cfgs/SUNCG/rpn_class_mask_5.yml
Q2: can you change the folder name from suncg_test_data/images to suncg_test_data/images_augmented, since i just noticed the image folder name is hardcoded in the data loader, ref: https://github.com/Sekunde/3D-SIS/blob/master/lib/datasets/dataset.py#L144-L149 then the images should be found accordingly
Q3: some suncg scenes are really big, thus we inference with a 24 GB GPU. You can change to use CPU by set parameters in https://github.com/Sekunde/3D-SIS/blob/master/lib/utils/config.py#L123-L124
If using more than 400 images and the volume is bigger than that threshold, it will automatically choose to inference on CPU. ref: https://github.com/Sekunde/3D-SIS/blob/master/lib/model/trainval.py#L664-L667 and https://github.com/Sekunde/3D-SIS/blob/master/lib/nets/network.py#L210-L214
